language: cpp

compiler:
- gcc
- clang
os:
 - linux

jobs:
  include:
  - name: "all projects"
    script:
    - cmake -H. -B_build
    - cmake --build _build
  - name: "each CMakeLists.txt"

script:
- source ./script
- cd /home/travis/build/navckin/lab006/solver_application/_build
- cpack -G DEB
    

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data

deploy: 
  provider: releases
  api_key:
    secure: "NClZh8XZALVR/BVrZPFqg95/zrk8F20oRekCzZhEcCQVigfsxJzQso95tzLTqvKHE0aTgWfYDK3/QVIbhF/iuD5FbYdqmk6lM8vrrb3TIXnCQhqQuxcoOYfm6siEAILXdL/Np2QzFjQ6atg1Ee2ZwxZrdgrDrF3W0VEP0W52s9vH13FlEB67NTec5rG0kT2o5Gv02nYJeNkHGwgjSvJXK4IsqodbTYJ0V2570D6bNFJAwmjBuEXNI0lNw1vpJGKKgeT1zpbY+IXbuygMMLqXidIpJm46iRYJ03RN8QsYKaseexJcd3cTtp8irp/ZNxC+8tH7QZAfUqbrS4Ug9Hc366fJROUYcZ7QgUDMRNW8fuCD9tEE1zrQVwMIaIwYkG1cuNKt9i4L2Qj8qbwQqAd7QjETkLkAmEk2rOOeoVhH49DMkwEyFTE59xflALJWwBDCWHshlOalRYjXX8yAXqaikAaY0o7OMirUlEK7EmMHWkvSCms1miHj2ipdEUBLtM+6Ea06ZNsQxj7d+XFaoMO1B+nNCKn6FWBeLp2RwxnjjeqYqKEmIt0huGKF9Bz8fDSE31V4/oRpsd52lTRTQXoEV1wB0/+WFIRrI0levJcK8DVmuOfWuR7Ypf0ZD3b/DrVLHMqwsm75ycaBRjIUfch4RQhhrRG0m1TKh3MaJBK1IEE="
    
  file: "/home/travis/build/navckin/lab006/solver_application/_build/solver-0.1.0.0-Linux.deb"
  cleanup: false
  on:
    branch: homework


